export const LOGIN_UI = {
  title: 'Bienvenido de nuevo',
  subtitle: 'Ingresa tus credenciales para acceder a tu cuenta',
  setupTotpTitle: 'Configura tu MFA',
  confirmEmailOtpTitle: 'Revisa tu correo',
  confirmTotpTitle: 'Autenticación en 2 Pasos',
  setupTotpDescription: 'Escanea este QR con tu app de autenticación o Authy, y escribe el código de 6 dígitos que se genera.',
  confirmEmailOtpDescription: (email) => `Te acabamos de enviar un código temporal a ${email}. Cópialo aquí para ingresar.`,
  confirmTotpDescription: 'Ingresa el código de 6 dígitos que aparece en tu aplicación de autenticación dinámica.',
  verifyAndEnter: 'Verificar e Ingresar',
  cancel: 'Cancelar',
  switchToPassword: 'Iniciar sesión con contraseña',
  emailLabel: 'Correo electrónico',
  emailPlaceholder: 'tu@correo.com',
  rememberOtp: 'Recordar este equipo (no pedirá códigos en el futuro)',
  continue: 'Continuar',
  passwordLabel: 'Contraseña',
  forgotPassword: '¿La olvidaste?',
  passwordPlaceholder: '••••••••',
  rememberPassword: 'Recordar este equipo (no pedirá MFA en el futuro)',
  enter: 'Ingresar',
  resetTitle: 'Recuperar contraseña',
  resetSubtitle: 'Te enviaremos un código para que puedas crear una nueva contraseña.',
  sendResetCode: 'Enviar código',
  resetCodeLabel: 'Código de verificación',
  resetCodePlaceholder: 'Ingresa el código que llegó a tu correo',
  resetNewPasswordLabel: 'Nueva contraseña',
  resetNewPasswordPlaceholder: 'Ingresa tu nueva contraseña',
  resetPasswordButton: 'Actualizar contraseña',
  resendResetCode: 'Enviar otro código',
  backToLogin: 'Volver al inicio de sesión',
  resetEmailRequired: 'Ingresa tu correo electrónico para recuperar tu contraseña.',
  resetCodeRequired: 'Ingresa el código de verificación.',
  resetCodeLengthError: 'El código debe tener 6 dígitos.',
  resetNewPasswordRequired: 'Ingresa una nueva contraseña.',
  resetSendCodeError: 'No se pudo enviar el código de recuperación.',
  resetConfirmError: 'No se pudo actualizar la contraseña.',
  resetCodeSent: (email) => `Te enviamos un código de verificación a ${email}.`,
  resetPasswordSuccess: 'Tu contraseña se actualizó correctamente.',
  switchToPasswordless: 'Ingresar sin contraseña',
  noAccount: '¿No tienes una cuenta?',
  signUp: 'Regístrate'
};

export const LOGIN_FLOW_TEXT = {
  appName: 'FocusMind',
  emailRequired: 'Por favor, ingresa tu correo electrónico primero.',
  passwordRequired: 'Por favor, ingresa tu contraseña.',
  emailCodeUnexpectedForPassword: 'El inicio de sesión con contraseña no debería pedir código por correo. Revisa en Cognito que no tengas MFA por email activo para este usuario.',
  missingPasswordFactor: 'Tu pool no ofrece factor de contraseña en este flujo.',
  emailOtpDisabled: 'Esta cuenta debe iniciar sesión con contraseña (y verificación MFA si corresponde).',
  factorSelectionError: (message) => `Error seleccionando factor: ${message}`,
  mfaSelectionError: (message) => `Error seleccionando MFA: ${message}`,
  unsupportedChallenge: (step) => `Reto no validado en UI: ${step}`,
  signInError: 'Error al iniciar sesión',
  remainingStep: (step) => `Aún falta un paso: ${step}`,
  invalidMfaCode: 'Código MFA inválido',
  emailOtpRetryError: 'No se pudo verificar el código de correo tras limpiar el dispositivo local.'
};

export const REGISTER_UI = {
  verifyEmailTitle: 'Verifica tu correo',
  verifyEmailPrefix: 'Hemos enviado un código a',
  verifyEmailSuffix: 'Ingresa el código a continuación para confirmar tu cuenta.',
  confirmAccount: 'Confirmar Cuenta',
  backToLogin: 'Volver a',
  login: 'Iniciar sesión',
  title: 'Crear una cuenta',
  subtitle: 'Únete y comienza tu camino',
  fullNameLabel: 'Nombre completo',
  fullNamePlaceholder: 'Juan Pérez',
  emailLabel: 'Correo electrónico',
  emailPlaceholder: 'tu@correo.com',
  passwordLabel: 'Contraseña',
  passwordPlaceholder: '••••••••',
  signUp: 'Registrarse',
  haveAccount: '¿Ya tienes una cuenta?',
  signIn: 'Iniciar sesión'
};

export const REGISTER_ERRORS = {
  signUpError: 'Error al registrar usuario',
  invalidCode: 'Código inválido'
};
